server {
    listen 80;
    server_name _;

    # 可选：更大传输（若你后续要上传）
    client_max_body_size 200m;

    # 将 /static/ 映射到 save_dir（必须以 / 结尾）
    location /static/ {
        alias /data/alarms/;
        autoindex on;                  # 如需目录列表可改为 on
        add_header Cache-Control "no-cache";
        # 可选：跨域（若用浏览器跨域访问）
        # add_header Access-Control-Allow-Origin *;
    }
}